import { createRequire } from 'module';
const require = createRequire('/node-tools/node_modules/');
const { chromium } = require('playwright');
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] });
const ctx = await browser.newContext({ viewport: { width: 1100, height: 620 } });
const page = await ctx.newPage();
const logs = [];
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) logs.push(m.type() + ': ' + m.text().slice(0, 300)); });
page.on('pageerror', (e) => logs.push('PAGEERROR: ' + e.message + '\n' + (e.stack || '')));
await page.addInitScript(() => { if (!localStorage.getItem('tlwh_settings_v1')) localStorage.setItem('tlwh_settings_v1', JSON.stringify({ quality: 'low' })); });
await page.goto('http://localhost:5173/');
await page.waitForFunction(() => window.__game && window.__game.ui.ready, null, { timeout: 90000 });
await page.screenshot({ path: '/tmp/e2e_start.png' });
console.log('start button text:', await page.$eval('#menu', (e) => e.innerText.replace(/\s+/g, ' ').slice(0, 160)));
await page.click('#btn-new');
await page.waitForTimeout(500);
const p0 = await page.evaluate(() => ({ x: window.__game.player.x, z: window.__game.player.z, began: window.__game.began, paused: window.__game.paused }));
await page.keyboard.down('KeyW');
await page.waitForTimeout(8000);
await page.keyboard.up('KeyW');
const p1 = await page.evaluate(() => ({ x: window.__game.player.x, z: window.__game.player.z, speed: window.__game.player.speed, hours: window.__game.time.hours, fps: window.__game.fpsAvg }));
console.log('before', JSON.stringify(p0), 'after 8s W', JSON.stringify(p1));
await page.screenshot({ path: '/tmp/e2e_walk.png' });
// save and reload -> Continue
await page.evaluate(() => window.__game.save());
await page.reload();
await page.waitForFunction(() => window.__game && window.__game.ui.ready, null, { timeout: 90000 });
console.log('after reload menu:', await page.$eval('#menu', (e) => e.innerText.replace(/\s+/g, ' ').slice(0, 120)));
const p2 = await page.evaluate(() => ({ x: window.__game.player.x, z: window.__game.player.z, hours: window.__game.time.hours }));
console.log('restored', JSON.stringify(p2));
await page.click('#btn-continue');
await page.waitForTimeout(500);
await page.keyboard.press('Escape');
console.log(logs.slice(0, 15).join('\n'));
await browser.close();
